name: Scala CI

on: [push]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Scala
      uses: olafurpg/setup-scala@v5
      with:
        java-version: openjdk@1.8
    - name: Run tests
      shell: bash
      run: sbt test
